package org.jtrim2.collections;

import org.junit.Test;

import static org.junit.Assert.*;

public class NaturalEqualityTest {
    @Test
    public void testAutoGenerated() {
        assertEquals(1, NaturalEquality.values().length);
        assertSame(
                NaturalEquality.INSTANCE,
                NaturalEquality.valueOf(NaturalEquality.INSTANCE.name()));
    }

    /**
     * Test of equals method, of class NaturalEquality.
     */
    @Test
    public void testEquals() {
        TestObject obj1 = new TestObject("OBJ1");

        assertFalse(NaturalEquality.INSTANCE.equals(null, obj1));
        assertFalse(NaturalEquality.INSTANCE.equals(obj1, null));
        assertFalse(NaturalEquality.INSTANCE.equals(obj1, new TestObject("OBJ2")));

        assertTrue(NaturalEquality.INSTANCE.equals(null, null));
        assertTrue(NaturalEquality.INSTANCE.equals(obj1, obj1));
        assertTrue(NaturalEquality.INSTANCE.equals(obj1, new TestObject("OBJ1")));
    }
}
