package org.jtrim2.event;

import org.junit.Test;

import static org.junit.Assert.*;
import static org.mockito.Mockito.*;

public class RunnableDispatcherTest {
    @Test
    public void testAutoGenerated() {
        assertEquals(1, RunnableDispatcher.values().length);
        assertSame(
                RunnableDispatcher.INSTANCE,
                RunnableDispatcher.valueOf(RunnableDispatcher.INSTANCE.name()));
    }

    @Test
    public void testDispatch() {
        Runnable listener = mock(Runnable.class);
        RunnableDispatcher.INSTANCE.onEvent(listener, null);
        verify(listener).run();
    }
}
