package org.jtrim2.event;

import org.junit.Test;

import static org.junit.Assert.*;

public class UnregisteredListenerRefTest {
    @Test
    public void testAutoGenerated() {
        assertEquals(1, UnregisteredListenerRef.values().length);
        assertSame(
                UnregisteredListenerRef.INSTANCE,
                UnregisteredListenerRef.valueOf(UnregisteredListenerRef.INSTANCE.toString()));
    }

    @Test
    public void testUnregister() {
        UnregisteredListenerRef.INSTANCE.unregister();
    }
}
