language: java
jdk:
  - oraclejdk7
  - openjdk7
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 800x600x24"
script: "gradle check -PprintTestErrorXmls"
