package org.jtrim2.property.swing;

import javax.swing.JPanel;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;

import static org.junit.Assert.*;

/**
 *
 * @author Kelemen Attila
 */
public class InvisibleGlassPaneFactoryTest {
    @BeforeClass
    public static void setUpClass() {
    }

    @AfterClass
    public static void tearDownClass() {
    }

    @Before
    public void setUp() {
    }

    @After
    public void tearDown() {
    }

    @Test
    public void testAutoGenerated() {
        assertEquals(1, InvisibleGlassPaneFactory.values().length);
        assertSame(
                InvisibleGlassPaneFactory.INSTANCE,
                InvisibleGlassPaneFactory.valueOf(InvisibleGlassPaneFactory.INSTANCE.name()));
    }

    @Test
    public void testCreatePanel() {
        JPanel invisiblePanel = InvisibleGlassPaneFactory.INSTANCE.createGlassPane();
        assertFalse(invisiblePanel.isOpaque());
        assertEquals(0, invisiblePanel.getBackground().getAlpha());
    }
}
