package org.jtrim2.property.swing;

import javax.swing.JPanel;
import org.junit.Test;

import static org.junit.Assert.*;

public class InvisibleGlassPaneFactoryTest {
    @Test
    public void testAutoGenerated() {
        assertEquals(1, InvisibleGlassPaneFactory.values().length);
        assertSame(
                InvisibleGlassPaneFactory.INSTANCE,
                InvisibleGlassPaneFactory.valueOf(InvisibleGlassPaneFactory.INSTANCE.name()));
    }

    @Test
    public void testCreatePanel() {
        JPanel invisiblePanel = InvisibleGlassPaneFactory.INSTANCE.createGlassPane();
        assertFalse(invisiblePanel.isOpaque());
        assertEquals(0, invisiblePanel.getBackground().getAlpha());
    }
}
