package org.jtrim2.cache;

import org.junit.Test;

import static org.junit.Assert.*;

public class ReferenceTypeTest {
    @Test
    public void testAutoGenerated() {
        for (ReferenceType state: ReferenceType.values()) {
            assertSame(state, ReferenceType.valueOf(state.toString()));
        }
    }
}
