package org.jtrim.collections;

import java.util.Objects;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;

import static org.junit.Assert.*;

/**
 *
 * @author Kelemen Attila
 */
public class NaturalEqualityTest {
    @BeforeClass
    public static void setUpClass() {
    }

    @AfterClass
    public static void tearDownClass() {
    }

    @Before
    public void setUp() {
    }

    @After
    public void tearDown() {
    }

    @Test
    public void testAutoGenerated() {
        assertEquals(1, NaturalEquality.values().length);
        assertSame(
                NaturalEquality.INSTANCE,
                NaturalEquality.valueOf(NaturalEquality.INSTANCE.name()));
    }

    /**
     * Test of equals method, of class NaturalEquality.
     */
    @Test
    public void testEquals() {
        TestObj obj1 = new TestObj("OBJ1");

        assertFalse(NaturalEquality.INSTANCE.equals(null, obj1));
        assertFalse(NaturalEquality.INSTANCE.equals(obj1, null));
        assertFalse(NaturalEquality.INSTANCE.equals(obj1, new TestObj("OBJ2")));

        assertTrue(NaturalEquality.INSTANCE.equals(null, null));
        assertTrue(NaturalEquality.INSTANCE.equals(obj1, obj1));
        assertTrue(NaturalEquality.INSTANCE.equals(obj1, new TestObj("OBJ1")));
    }

    private static final class TestObj {
        private final String str;

        public TestObj(String str) {
            this.str = str;
        }

        @Override
        public int hashCode() {
            int hash = 5;
            hash = 97 * hash + Objects.hashCode(str);
            return hash;
        }

        @Override
        public boolean equals(Object obj) {
            if (obj == null) return false;
            if (obj == this) return true;
            if (getClass() != obj.getClass()) return false;

            final TestObj other = (TestObj)obj;
            return Objects.equals(this.str, other.str);
        }
    }
}
