package org.jtrim.swing.access;

import java.awt.Component;
import javax.swing.JPanel;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;

import static org.junit.Assert.*;
import static org.mockito.Mockito.*;

/**
 *
 * @author Kelemen Attila
 */
public class InvisiblePanelFactoryTest {
    @BeforeClass
    public static void setUpClass() {
    }

    @AfterClass
    public static void tearDownClass() {
    }

    @Before
    public void setUp() {
    }

    @After
    public void tearDown() {
    }

    @Test
    public void testAutoGenerated() {
        assertEquals(1, InvisiblePanelFactory.values().length);
        assertSame(InvisiblePanelFactory.INSTANCE, InvisiblePanelFactory.valueOf(InvisiblePanelFactory.INSTANCE.toString()));
    }


    /**
     * Test of createPanel method, of class InvisiblePanelFactory.
     */
    @Test
    public void testCreatePanel() {
        Component dummyComponent = spy(new JPanel());
        JPanel invisiblePanel = InvisiblePanelFactory.INSTANCE.createPanel(dummyComponent);
        assertFalse(invisiblePanel.isOpaque());
        assertEquals(0, invisiblePanel.getBackground().getAlpha());

        verifyZeroInteractions(dummyComponent);
    }
}