package org.jtrim2.concurrent;

import org.junit.Test;

import static org.junit.Assert.*;

public class TaskStateTest {
    /**
     * Test of values method, of class TaskState.
     */
    @Test
    public void testAutoGenerated() {
        for (TaskState state: TaskState.values()) {
            assertSame(state, TaskState.valueOf(state.toString()));
        }
    }

    /**
     * Test of isDone method, of class TaskState.
     */
    @Test
    public void testIsDone() {
        assertFalse(TaskState.NOT_STARTED.isDone());
        assertFalse(TaskState.RUNNING.isDone());
        assertTrue(TaskState.DONE_CANCELED.isDone());
        assertTrue(TaskState.DONE_COMPLETED.isDone());
        assertTrue(TaskState.DONE_ERROR.isDone());
        assertEquals("All states must be tested", 5, TaskState.values().length);
    }
}
