package org.jtrim2.image.transform;

import org.junit.Test;

import static org.junit.Assert.*;

public class ZoomToFitOptionTest {
    @Test
    public void testAutoGenerated() {
        for (ZoomToFitOption state: ZoomToFitOption.values()) {
            assertSame(state, ZoomToFitOption.valueOf(state.toString()));
        }
    }
}
