package org.jtrim.property;

import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;

import static org.junit.Assert.*;
import static org.mockito.Mockito.*;

/**
 *
 * @author Kelemen Attila
 */
public class RunnableDispatcherTest {
    // Test it just for the sake of completeness

    @BeforeClass
    public static void setUpClass() {
    }

    @AfterClass
    public static void tearDownClass() {
    }

    @Before
    public void setUp() {
    }

    @After
    public void tearDown() {
    }

    @Test
    public void testAutoGenerated() {
        assertEquals(1, RunnableDispatcher.values().length);
        assertSame(
                RunnableDispatcher.INSTANCE,
                RunnableDispatcher.valueOf(RunnableDispatcher.INSTANCE.name()));
    }

    @Test
    public void testOnEvent() {
        Runnable listener = mock(Runnable.class);
        RunnableDispatcher.INSTANCE.onEvent(listener, null);
        verify(listener).run();
    }
}
