name: Default Test Action
on:
  push:
    branches:
      - master
      - github_actions_test
jobs:
  test:
    runs-on: ubuntu-latest
    concurrency: master_push_group
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Set up JDK 8 for compilation
        uses: actions/setup-java@v2.5.0
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Set up JDK 17 for Build
        uses: actions/setup-java@v2.5.0
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Run tests with XVFB
        uses: GabrielBB/xvfb-action@add653c7ca46237f2fad73a6ae95edfea0835443
        with:
          run: ./gradlew clean build jacocoTestReport -PenableJacocoXmlReport=true -PprintTestErrorXmls
