name: Tests
on:
  push:
    branches:
      - master
      - github_actions_test
jobs:
  test:
    runs-on: ubuntu-latest
    concurrency: master_push_group
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Set up JDK 11 for compilation
        uses: actions/setup-java@v2.5.0
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Set up JDK 17 for Build
        uses: actions/setup-java@v2.5.0
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Run tests with XVFB
        id: test_default
        uses: GabrielBB/xvfb-action@add653c7ca46237f2fad73a6ae95edfea0835443
        with:
          run: ./gradlew --continue clean build jacocoTestReport -PenableJacocoXmlReport=true
      - name: Upload Test Report
        uses: actions/upload-artifact@v2.3.1
        if: failure() && steps.test_default.outcome == 'failure'
        with:
          name: junit-reports
          path: subprojects/*/build/reports/tests/test/**
          retention-days: 30
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v2.3.1
        if: steps.test_default.outcome == 'success'
        with:
          name: jacoco-reports
          path: build/reports/jacoco/jacocoTestReport/html/**
          retention-days: 30
      - name: Run tests (Java 17) with XVFB
        id: test_J17
        uses: GabrielBB/xvfb-action@add653c7ca46237f2fad73a6ae95edfea0835443
        with:
          run: ./gradlew --continue clean build -PcompileJavaVersion=17
      - name: Upload Test Report (Java 17)
        uses: actions/upload-artifact@v2.3.1
        if: failure() && steps.test_J17.outcome == 'failure'
        with:
          name: junit-reports-17
          path: subprojects/*/build/reports/tests/test/**
          retention-days: 30
